### ISSUE TITLE
User for mysql container user is called POSTGRES_USER

### ISSUE THREAD

**Issue by mattkrems-schireson** [schireson/pytest-mock-resources#116]
https://github.com/schireson/pytest-mock-resources/blob/c5e715c46d87a1239161f7e55199dff77e056564/src/pytest_mock_resources/container/mysql.py#L99

**Comment by DanCardin** [comment]
https://github.com/schireson/pytest-mock-resources/pull/118 to be released soon

**Comment by DanCardin** [comment]
Fixed in 2.1.2
