### ISSUE TITLE
Dependabot warning for docker subdependency

### ISSUE THREAD

**Issue by bryancusatis** [schireson/pytest-mock-resources#156]
**Describe the bug**
Dependabot alert for docker dependency. 

**Environment**
* Windows
* 3.9

**To Reproduce**
Getting dependabot alert for pywin32 which is being used by docker dependency. See below image. 

![Capture](https://user-images.githubusercontent.com/641046/179639016-81722f9e-63fe-4edd-a318-0619f825cfdb.PNG)

**Additional context**
It appears there are thoughts of abandoning the docker python repo. Refer to this comment as a possible alternative https://github.com/docker/docker-py/pull/2989#issuecomment-1179720247.

**Comment by DanCardin** [comment]
Thanks for the suggestion. I had been following that thread, but wasn't previously aware of that alternative library. It's likely a good candidate substitution.

**Comment by DanCardin** [comment]
lmk if you run into any issues, 2.4.3 switches to python-on-whales

**Comment by bryancusatis** [comment]
awesome! thanks
