### ISSUE TITLE
Support SQLAlchemy 1.4 future mode

### ISSUE THREAD

**Issue by mje-nz** [schireson/pytest-mock-resources#177]
**Is your feature request related to a problem? Please describe.**
SQLAlchemy 1.4 Engines and Sessions have a future mode which we're supposed to use to prepare for 2.0, but PMR doesn't support passing additional parameters to `Engine.__init__`, so we can't enable it for our tests.

**Describe the solution you'd like**
Either a `future: bool` parameter to MysqlConfig and PostgresConfig which sets future on Engines and Sessions, or an `engine_options: dict` parameter to allow arbitrary extra parameters for `Engine.__init__` (and then we can use a sessionmaker to futurize the Session)? I'm happy to implement it, I just don't want to step on anyone's toes.

**Comment by DanCardin** [comment]
i believe postgres supports and `engine_kwargs` argument. although you're right, i dont think mysql currently has it implemented

**Comment by DanCardin** [comment]
I believe the `session=True` argument also accepts a sessionmaker/Session cls. So you can also customize the sort of session object you get back that way, for what it's worth.

**Comment by DanCardin** [comment]
v2.6.6 Adds support to mysql. Lmk if this doesn't do it for you and I can reopen

**Comment by mje-nz** [comment]
Perfect, thanks :)
