### ISSUE TITLE
Dependency on attrs package should be explicit

### ISSUE THREAD

**Issue by bluetech** [schireson/pytest-mock-resources#179]
Hi, I'm one of the pytest maintainers.

I am working on a PR to pytest that will remove the attrs dependency. This means that plugins that use attrs but do not explicitly require it will break. From a search among pytest plugins, I found that pytest-mock-resources is one such plugin.

attrs is used in this file: https://github.com/schireson/pytest-mock-resources/blob/d522be82cd3a08b886fb504429b315f30d7280eb/src/pytest_mock_resources/patch/redshift/mock_s3_copy.py

**Comment by bluetech** [comment]
The pytest PR is this: https://github.com/pytest-dev/pytest/pull/10669

**Comment by DanCardin** [comment]
v2.6.7 wont have this defect
