### ISSUE TITLE
Getting errors when using `create_redis_fixture`

### ISSUE THREAD

**Issue by miguelsousa** [schireson/pytest-mock-resources#187]
**Describe the bug**
I'm trying to use `pytest-mock-resources` for the first time to mock a Redis client. I've used the instructions at https://pytest-mock-resources.readthedocs.io/en/latest/redis.html as a guidance, but I'm running into errors. Not sure if they're caused by bugs, or if I'm doing something wrong with the API. Thanks in advance.

**Environment**
* Host OS: macOS
* Docker image if applicable: n/a
* Python Version: 3.9.16
* Virtualenv/Pyenv etc.. if applicable

**To Reproduce**
1. Save the two snippets below as **myapp.py** and **test_myapp.py**
2. Run `python -m pip install pytest redis pytest-mock-resources` to install the necessary dependencies
3. Run `python -m pytest`

**Expected behavior**
The two tests — `test_set_item` and `test_set_item2` — contained in **test_myapp.py** should succeed.

**Actual Behavior**
Both tests fail. The result is shown below.
```
FAILED test_myapp.py::test_set_item - AttributeError: 'function' object has no attribute 'hset'
ERROR test_myapp.py::test_set_item2 - AttributeError: 'function' object has no attribute 'pmr_credentials'
```

**Additional context**
Contents of **myapp.py**
```python
from redis import Redis

REDIS_CLIENT = Redis(host='localhost', port=6379, db=0)
REDIS_KEY = "some:key"

def set_item(idx, value):
    REDIS_CLIENT.hset(REDIS_KEY, idx, value)
```

Contents of **test_myapp.py**
```python
from unittest.mock import patch

import pytest
from pytest_mock_resources import create_redis_fixture
from redis import Redis

from myapp import set_item, REDIS_KEY


@pytest.fixture
def redis_client_fixt():
    yield create_redis_fixture()


def test_set_item(redis_client_fixt):
    with patch('myapp.REDIS_CLIENT', redis_client_fixt) as redis_client:
        idx = 1234
        value = "some_value"
        set_item(idx, value)

        assert redis_client.hget(REDIS_KEY, idx) == value


@pytest.fixture
def redis_client_fixt2():
    redis = create_redis_fixture()
    yield Redis(**redis.pmr_credentials.as_redis_kwargs())


def test_set_item2(redis_client_fixt2):
    with patch('myapp.REDIS_CLIENT', redis_client_fixt2) as redis_client:
        idx = 1234
        value = "some_value"
        set_item(idx, value)

        assert redis_client.hget(REDIS_KEY, idx) == value
```

**Comment by miguelsousa** [comment]
@DanCardin thanks for the feedback. Here's an updated **test_myapp.py** that works:
```python
from unittest.mock import patch
from pytest_mock_resources import create_redis_fixture
from myapp import set_item, REDIS_KEY

redis_client_fixt = create_redis_fixture()

def test_set_item(redis_client_fixt):
    with patch('myapp.REDIS_CLIENT', redis_client_fixt) as redis_client:
        idx = 1234
        value = b"some_value"
        set_item(idx, value)

        assert redis_client.hget(REDIS_KEY, idx) == value
```

It's worth mentioning that the module `python_on_whales` had to be installed (`python -m pip install python-on-whales`) and a `redis` Docker image was pulled the first time the test ran.

**Comment by DanCardin** [comment]
you can ensure `python_on_whales` is installed by using the "docker" extra (i.e. `pip install pytest-mock-resources[docker]`
