### ISSUE TITLE
Redis Container dont start after update Docker for Desktop on windows.

### ISSUE THREAD

**Issue by nische** [schireson/pytest-mock-resources#200]
Hi Guys, 

I have the Problem that  my create_redis_fixture dont start the Docker container after updated Docker Desktop to v4.25.2 on Windows. 
My Project worked before the update without Problems. 

I can actual run containers with "python-on-whales" from my python shell. 

I use python 3.10.11 with pytest-mock-resource v2.9.2 on windows with a venv.

```
 pip list
Package               Version   Editable project location
--------------------- --------- ----------------------------------------------
annotated-types       0.5.0
astroid               2.15.6
async-timeout         4.0.3
autopep8              2.0.4
certifi               2023.7.22
chardet               5.2.0
charset-normalizer    3.2.0
click                 8.1.7
colorama              0.4.6
commonmark            0.9.1
coverage              7.3.1
dacite                1.8.1
dill                  0.3.7
EPCPyYes              2.0.5
exceptiongroup        1.1.3
filelock              3.12.3
greenlet              2.0.2
httmock               1.4.0
idna                  3.4
iniconfig             2.0.0
isort                 5.12.0
Jinja2                3.1.2
lazy-object-proxy     1.9.0
litequeue             0.7
lxml                  4.9.3
MarkupSafe            2.1.3
mccabe                0.7.0
packaging             23.1
pip                   23.2.1
platformdirs          3.10.0
pluggy                1.3.0
pycodestyle           2.11.0
pydantic              2.3.0
pydantic_core         2.6.3
pylint                2.17.5
PyMuPDF               1.23.6
PyMuPDFb              1.23.6
PyPDF2                3.0.1
pytest                7.4.2
pytest-cov            4.1.0
pytest-env            1.0.1
pytest-mock           3.11.1
pytest-mock-resources 2.9.2
python-on-whales      0.64.3
redis                 5.0.0
requests              2.31.0
requests-mock         1.11.0
setuptools            65.5.0
six                   1.16.0
SQLAlchemy            2.0.22
tomli                 2.0.1
tomlkit               0.12.1
tqdm                  4.66.1
typer                 0.9.0
typing_extensions     4.7.1
urllib3               2.0.4
wrapt                 1.15.0
xmltodict             0.13.0
```
Did anybody know this problem?

BR,

NiSche

**Comment by DanCardin** [comment]
Is pytest-mock-resources timing out or hanging? or what does "dont start" mean.

I know in the past i've needed to `docker pull redis:5.0.7` ahead of running the tests due to slow network speed. if you dont have the image in question ahead of time it will pull it and potentially introduce longer startup time than we allow for in our timeouts.

**Comment by nische** [comment]
Thanks for your answer

The Image is already on my system.
The package throws the exeption below. And if i watch docker desktop gui the container dont start (and it did before the update) 

```
self = Connection<host=host.docker.internal,port=6380,db=0>
    def connect(self):
        "Connects to the Redis server if not already connected"
        if self._sock:
            return
        try:
>           sock = self.retry.call_with_retry(
                lambda: self._connect(), lambda error: self.disconnect(error)
            )
.venv\lib\site-packages\redis\connection.py:259: 
```

**Comment by nische** [comment]
pruning the system doesnt fix it. And i have the same error on the new notebook of my colleague.

Did you have any idee?

**Comment by DanCardin** [comment]
The only other thing I can think of is that the host correct for your docker setup. If you can import `python_on_whales` or docker-py, construct a client yourself, and create a container yourself, then it's almost certainly that you need to explicitly export the `PYTEST_MOCK_RESOURCES_HOST` env var to a different value.

If that **doesnt** work, then the problem is definitely outside PMR itself.

**Comment by nische** [comment]
That's what I do last week. I use pytest-docker and create the Redis service with this as a fixture. 👍

I wish you a Merry Christmas and a happy new year. 

Br, Nische
