### ISSUE TITLE
Drop python 2.7 support

### ISSUE THREAD

**Issue by DanCardin** [schireson/pytest-mock-resources#78]
**Is your feature request related to a problem? Please describe.**
It's a maintenance burden, and pytest itself only supports 2.7 up to 4.6.X.

We should maybe produce a final, minor release with 2.7 support so we can theoretically have a clean 1.x.Y version off which to backport things onto Y if it ever became important.

**Comment by kpitzen** [comment]
Just stopping by to express my support for resolving this issue.

**Comment by DanCardin** [comment]
As of version 2.0 python 2 was dropped
